language: python
python:
- "3.6"
- "3.7"

install:
- pip3 install -r requirements.txt

scripts:
- python3 -m unittest discover tests/ "model_test.py"
- python3 -m unittest discover tests/ "data_collection_test.py"
